import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {project,ready,percent,validateOutput,validateImport,invalidate} from '../src/state.js';
import {completion,endpoint,runRole} from '../src/engine.js';
const agents=JSON.parse(await readFile(new URL('../agents.json',import.meta.url))).agents;
const make=()=>project('科研问题','限定原文证据与真实角色产物',agents);
function envelope(p,a){return {schema_version:'1.0',project_id:p.id,agent_id:a.agent_id,summary:'仅为测试夹具的角色输出，用于核查合同和工具执行，不是科研结论。',evidence_refs:[],limitations:['测试不验证真实科研质量'],claims:[],unresolved_issues:[],payload:Object.fromEntries(a.required_payload.map(k=>[k,'测试夹具的实质字段']))};}
test('44-role DAG, native percent and review dependencies',()=>{const p=make();assert.equal(agents.length,44);assert.ok(ready(p,agents[0]));const child=agents.find(a=>a.dependencies.includes('M00'));assert.equal(ready(p,child),false);p.tasks.M00.state='awaiting_review';assert.equal(percent(p),0);p.tasks.M00.state='completed';assert.equal(percent(p),2.3);assert.equal(ready(p,child),true);});
test('S-source IDs cannot replace E-evidence IDs, metadata cannot substantiate claims',()=>{const p=make(),a=agents[0],o=envelope(p,a);o.evidence_refs=['S-one'];assert.throws(()=>validateOutput(o,p,a),/E-/);o.evidence_refs=['E-one'];p.evidence=[{id:'E-one',level:'metadata'}];o.claims=[{claim_id:'C1',text:'医疗结论',inference_level:'direct',evidence_ids:['E-one']}];assert.throws(()=>validateOutput(o,p,a),/题录/);});
test('interrupted restore and invalidation preserve run audit, revoke gates',()=>{const p=make();p.tasks.M00.state='running';assert.equal(validateImport(p,agents).tasks.M00.state,'interrupted');p.tasks.M00.runs.push({id:'old-run'});p.gates.G0={approved:true};invalidate(p,agents,'M00');assert.equal(p.tasks.M00.runs.length,1);assert.deepEqual(p.gates,{});assert.equal(p.tasks.M00.state,'pending');});
test('API endpoint cannot leak key through URL and plaintext remote transport forbidden',()=>{assert.throws(()=>endpoint('https://key:secret@example.com/v1'));assert.throws(()=>endpoint('http://example.com/v1'));assert.equal(endpoint('https://example.com/v1/'),'https://example.com/v1/chat/completions');});
test('stream records real reasoning and usage; incomplete stream rejected',async()=>{const fragments=[],usage=[];const body='data: '+JSON.stringify({choices:[{delta:{reasoning_content:'实际测试思考片段'}}]})+'\n\ndata: '+JSON.stringify({choices:[{delta:{content:'OK'}}],usage:{prompt_tokens:2,completion_tokens:1}})+'\n\ndata: [DONE]\n\n';const fake=async()=>new Response(body,{headers:{'content-type':'text/event-stream'}});const result=await completion({base:'https://example.com/v1',model:'fixture',key:'fixture'},[],undefined,(...e)=>fragments.push(e),u=>usage.push(u),fake);assert.equal(result,'OK');assert.equal(usage[0].prompt_tokens,2);assert.ok(fragments.some(f=>f[0]==='思考片段'));await assert.rejects(completion({base:'https://example.com/v1',model:'x',key:'x'},[],undefined,()=>{},()=>{},async()=>new Response(body.replace('data: [DONE]\n\n',''),{headers:{'content-type':'text/event-stream'}})),/中断/);});
test('actual upstream Pi loop executes host tools and validates final fixture',async()=>{const p=make(),a=agents[0],events=[];let calls=0;const fake=async()=>{calls++;const plan=calls===1?{action:'tools',tool_calls:[{name:'project.read',args_json:'{}'},{name:'evidence.read',args_json:'{}'}],final_json:''}:{action:'final',tool_calls:[],final_json:JSON.stringify(envelope(p,a))};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(plan)},finish_reason:'stop'}],usage:{prompt_tokens:20,completion_tokens:5}}),{headers:{'content-type':'application/json'}});};const result=await runRole(p,a,{base:'https://example.com/v1',model:'fixture',key:'fixture'},(k,v)=>events.push([k,v]),()=>{},{fetcher:fake});assert.equal(result.output.agent_id,'M00');assert.equal(calls,2);assert.ok(events.some(e=>e[0]==='工具执行完成'&&e[1]==='project.read'));assert.ok(events.some(e=>e[0]==='Pi tool_execution_end'));assert.equal(p.usage.input,40);assert.equal(p.usage.unknown,0);});
