import {project,ready,percent,gates,invalidate,validateImport} from './state.js';
import {completion,runRole} from './engine.js';
const $=id=>document.getElementById(id), text=(id,value)=>$(id).textContent=value;
let agents=[],projects=[],p=null,running=false,paused=false,activeAgent=null,tab='workspace',stream='',db,connected=false;
const labels={pending:'待执行',running:'执行中',awaiting_review:'待审阅',completed:'已通过',failed:'失败',interrupted:'已中断'};
const categories={M:'总控',L:'文献调研',A:'架构设计',W:'科研写作',F:'科研绘图',Q:'质量审阅',P:'平台与交付'};
function notice(message){text('notice',message);}
function el(tag,className,value){const n=document.createElement(tag);if(className)n.className=className;if(value!==undefined)n.textContent=value;return n;}
const requestPromise=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
async function initDB(){db=await requestPromise(Object.assign(indexedDB.open('reviewforge-v1',1),{onupgradeneeded:e=>e.target.result.createObjectStore('projects',{keyPath:'id'})}));projects=await requestPromise(db.transaction('projects').objectStore('projects').getAll());for(const q of projects){for(const t of Object.values(q.tasks))if(t.state==='running'){t.state='interrupted';t.error='页面已退出，上次执行中断；重新运行需再输入密钥';}p=q;await save();}p=projects.sort((a,b)=>b.created.localeCompare(a.created))[0]||null;}
function save(){if(!p)return Promise.resolve();const snapshot=structuredClone(p);return new Promise((resolve,reject)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(snapshot);tx.oncomplete=resolve;tx.onerror=()=>{paused=true;notice('本地保存失败，请立即导出备份；后续执行已暂停');reject(tx.error);};});}
function event(kind,detail=''){if(!p)return;const now=new Date().toISOString();if(['思考片段','生成片段'].includes(kind)){stream+=(kind==='思考片段'?'[思考] ':'')+detail;text('stream',stream.slice(-24000));return;}p.events.push({at:now,kind,detail});if(p.events.length>1500)p.events.shift();text('activity',kind+(detail?' · '+detail:''));renderEvents();void save().catch(()=>{});}
function settings(){return {base:$('base').value.trim(),model:$('model').value.trim(),key:$('key').value.trim(),onAgent:a=>{activeAgent=a;}};}
function changeTab(id){tab=id;document.querySelectorAll('.tab').forEach(n=>n.classList.toggle('hidden',n.id!==id));document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('active',n.dataset.tab===id));render();}
function renderEvents(){const box=$('events');box.replaceChildren();for(const e of (p?.events||[]).slice(-60).reverse()){const row=el('div','event',e.kind+(e.detail?' · '+e.detail:''));row.append(el('small','',new Date(e.at).toLocaleString()));box.append(row);}}
function render(){
  const select=$('projectSelect');select.replaceChildren();if(!projects.length)select.append(new Option('尚无项目',''));for(const q of projects)select.append(new Option(q.title,q.id,false,q.id===p?.id));select.disabled=running;
  text('projectTitle',p?.title||'准备你的第一篇综述');text('projectBrief',p?.brief||'创建课题，导入来源并建立证据卡，然后启动智能体。');text('percent',p?percent(p):0);$('progress').value=p?Object.values(p.tasks).filter(t=>t.state==='completed').length:0;
  text('counts',p?`${$('progress').value} 个已通过 · ${Object.values(p.tasks).filter(t=>t.state==='awaiting_review').length} 个待审阅`:'0 个已通过');
  text('activity',running?(paused?'暂停请求已记录，等待当前角色结束':p?.events.at(-1)?.kind||'执行中'):p?.events.at(-1)?.kind||'等待启动');
  text('usage',`已知 token ${p?((p.usage.input||0)+(p.usage.output||0)).toLocaleString():0} · ${p?.usage.unknown||0} 次用量未知`);
  $('start').disabled=!p||running;$('pause').disabled=!running;$('abort').disabled=!running;
  const box=$('matrix');box.replaceChildren();for(const a of agents.filter(a=>!$('category').value||a.category===$('category').value)){const t=p?.tasks[a.agent_id];const b=el('button','agent '+(t?.state||'pending'));const top=el('div','agent-top');top.append(el('span','agent-id',a.agent_id+' / '+categories[a.category]),el('span','badge',labels[t?.state||'pending']));b.append(top,el('span','agent-name',a.name),el('span','agent-desc',a.responsibility));b.onclick=()=>{$('reportRole').value=a.agent_id;changeTab('reports');};box.append(b);}
  renderEvents();if(tab==='evidence')renderEvidence();if(tab==='reports')renderReports();if(tab==='memory')renderMemory();
}
function renderEvidence(){const box=$('sourceList');box.replaceChildren();const select=$('evidenceSource'),old=select.value;select.replaceChildren();for(const s of p?.sources||[]){select.append(new Option(s.id+' · '+s.name,s.id,false,s.id===old));const row=el('div','item');row.append(el('b','',s.id+' · '+s.name),el('p','',s.text.length+' 字符 / SHA256 '+s.sha256),el('pre','',s.text.slice(0,900)));box.append(row);}const list=$('evidenceList');list.replaceChildren();for(const e of p?.evidence||[]){const row=el('div','item');row.append(el('b','',e.id+' · '+e.source_id+' · '+e.level),el('p','',e.locator),el('pre','',e.quote));list.append(row);}}
function renderReports(){const id=$('reportRole').value,a=agents.find(a=>a.agent_id===id),t=p?.tasks[id];text('reportTitle',a?a.agent_id+' · '+a.name:'选择一个角色');text('reportBody',t?JSON.stringify({state:t.state,error:t.error||null,review:t.review||null,output:t.output||null,run_history:t.runs},null,2):'创建项目后查看报告');$('approve').disabled=running||t?.state!=='awaiting_review';$('revise').disabled=running||!t?.output;
  $('retry').disabled=running||!['failed','interrupted'].includes(t?.state);
  const box=$('gates');box.replaceChildren();for(const [id,deps] of Object.entries({...gates,G5:agents.map(a=>a.agent_id)})){const ok=p&&deps.every(d=>p.tasks[d]?.state==='completed')&&(id!=='G5'||Object.keys(gates).every(g=>p.gates[g]?.approved));const row=el('div','gate');row.append(el('span','',id+' · '+(p?.gates[id]?.approved?'已批准':ok?'待人工批准':'依赖未完成')));const b=el('button','',id==='G5'?'批准为最终候选':'批准质量门');b.disabled=!ok||running||p?.gates[id]?.approved;b.onclick=async()=>{const reason=$('reviewComment').value.trim();if(!reason){notice('请在审阅意见中填写这道质量门的核查依据');return;}p.gates[id]={approved:true,at:new Date().toISOString(),reason};event('人工批准质量门',id);await save();render();};row.append(b);box.append(row);}}
function renderMemory(){const box=$('memoryList');box.replaceChildren();for(const e of p?.experiences||[]){const row=el('div','item');row.append(el('b','',e.role+' · '+(e.validated?'已提升':'待校验候选')),el('pre','',e.lesson));if(!e.validated){const b=el('button','','经核查提升此经验');b.disabled=running;b.onclick=async()=>{if(!p.tasks[e.role]?.review?.verdict||p.tasks[e.role].review.verdict!=='pass'){notice('先完成对应角色产物的人工审阅');return;}e.validated=true;e.validated_at=new Date().toISOString();await save();renderMemory();};row.append(b);}box.append(row);}if(!box.children.length)box.append(el('p','muted','角色产物中的经验候选会在这里积累。'));}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function executeReady(){
  if(!p)return;if(!settings().key){notice('请先在“模型连接”中输入 API key');changeTab('settings');return;}if(!connected){notice('请先测试模型连接');changeTab('settings');return;}
  running=true;paused=false;notice('');try{while(!paused){const role=agents.find(a=>ready(p,a));if(!role){event('等待人工处理','审阅产物、批准质量门，或重试失败角色后继续');break;}const t=p.tasks[role.agent_id];t.state='running';t.error=null;stream='';text('stream','');const record={id:crypto.randomUUID(),started:new Date().toISOString(),model:settings().model,state:'running',events_start:p.events.length};t.runs.push(record);event('角色启动',role.agent_id+' '+role.name);await save();render();
      try{const result=await runRole(p,role,settings(),event,()=>{void save().catch(()=>{});});t.output=result.output;record.output=result.output;if(result.blind_review)record.blind_review=result.blind_review;t.state='awaiting_review';record.state='awaiting_review';record.turns=result.turns;const lesson=result.output.payload.experience_candidates;if(lesson)p.experiences.push({id:crypto.randomUUID(),role:role.agent_id,lesson,validated:false,run_id:record.id});event('角色产物待审阅',role.agent_id+'；尚未计入完成进度');}
      catch(e){t.state='failed';record.state='failed';t.error=e.message;record.error=e.message;event('角色执行失败',role.agent_id+' · '+e.message);paused=true;}
      finally{activeAgent=null;record.ended=new Date().toISOString();await save();render();}
    }}catch(e){notice(e.message);}finally{running=false;activeAgent=null;render();}
}
document.querySelectorAll('[data-tab]').forEach(n=>n.onclick=()=>changeTab(n.dataset.tab));$('category').onchange=render;
$('newProject').onclick=()=>{if(running){notice('先暂停并等待当前角色结束');return;}$('createDialog').showModal();};
$('createDialog').addEventListener('close',async()=>{if($('createDialog').returnValue!=='create')return;p=project($('newTitle').value.trim(),$('newBrief').value.trim(),agents);p.experiences=projects.flatMap(q=>q.experiences.filter(e=>e.validated)).map(e=>structuredClone(e));projects.push(p);await save();event('项目已创建',p.title);render();});
$('projectSelect').onchange=()=>{if(running)return;p=projects.find(q=>q.id===$('projectSelect').value);stream='';text('stream','等待模型请求');render();};
$('start').onclick=async()=>{if(!navigator.locks){notice('浏览器缺少任务锁功能，请使用现代 Chrome / Edge / Firefox');return;}await navigator.locks.request('reviewforge-v1-executor',{ifAvailable:true},async lock=>{if(!lock){notice('另一个页面正在执行任务，请先在该页面暂停');return;}await executeReady();});};$('pause').onclick=()=>{paused=true;event('暂停后续任务','当前角色结束后停止；请求仍在执行');render();};$('abort').onclick=()=>{paused=true;activeAgent?.abort();event('已请求中止','浏览器停止接收；远端用量可能未知');};
$('backup').onclick=()=>{if(p)download('reviewforge-'+p.id+'.json',p);};
$('restore').onchange=async()=>{try{if(running)throw Error('先暂停并等待角色结束');const file=$('restore').files[0];if(!file)return;if(file.size>30*1024*1024)throw Error('备份超过 30 MB');const q=validateImport(JSON.parse(await file.text()),agents);for(const s of q.sources){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s.text)))).map(b=>b.toString(16).padStart(2,'0')).join('');if(hash!==s.sha256)throw Error('来源哈希不匹配');}if(projects.some(x=>x.id===q.id))throw Error('该项目已存在，避免覆盖请在另一浏览器导入');p=q;projects.push(q);await save();event('备份已导入');render();}catch(e){notice(e.message);}finally{$('restore').value='';}};
$('sources').onchange=async()=>{try{if(!p)throw Error('先创建项目');if(running||Object.values(p.tasks).some(t=>t.output))throw Error('来源集在角色产物生成后锁定；新增文献请新建项目，避免旧结论失效');for(const f of $('sources').files){if(f.size>4*1024*1024)throw Error('单篇文本限制 4 MB');const content=await f.text();if(!content.trim())continue;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content)))).map(b=>b.toString(16).padStart(2,'0')).join('');if(p.sources.some(s=>s.sha256===hash))continue;p.sources.push({id:'S-'+crypto.randomUUID().slice(0,8),name:f.name,text:content,sha256:hash,imported:new Date().toISOString()});}await save();event('文献导入完成',p.sources.length+' 篇来源');renderEvidence();}catch(e){notice(e.message);}finally{$('sources').value='';}};
$('addEvidence').onclick=async()=>{try{if(!p)throw Error('先创建项目');if(running||Object.values(p.tasks).some(t=>t.output))throw Error('证据集在产物生成后锁定；新增证据请创建新项目');const s=p.sources.find(s=>s.id===$('evidenceSource').value),quote=$('quote').value;if(!s||!quote||!s.text.includes(quote))throw Error('引句必须是来源中的连续原文');if(!$('locator').value.trim())throw Error('请填写原文定位');p.evidence.push({id:'E-'+crypto.randomUUID().slice(0,8),source_id:s.id,quote,locator:$('locator').value.trim(),level:$('evidenceLevel').value});await save();renderEvidence();notice('证据卡已保存');}catch(e){notice(e.message);}};
$('reportRole').onchange=renderReports;
$('approve').onclick=async()=>{const t=p?.tasks[$('reportRole').value],comment=$('reviewComment').value.trim();if(!t||t.state!=='awaiting_review'||running)return;if(!comment){notice('请填写人工审阅依据');return;}t.review={verdict:'pass',actor:'human',at:new Date().toISOString(),comment};t.state='completed';event('角色审阅通过',$('reportRole').value);await save();render();};
$('revise').onclick=async()=>{if(!p||running)return;const id=$('reportRole').value,comment=$('reviewComment').value.trim();if(!comment){notice('请填写修改要求');return;}const affected=invalidate(p,agents,id);p.tasks[id].revision=comment;event('退回修改',id+'，'+affected.size+' 个角色与质量门重置，历史运行保留');await save();render();};
$('retry').onclick=async()=>{const t=p?.tasks[$('reportRole').value];if(!running&&t&&['failed','interrupted'].includes(t.state)){t.state='pending';await save();render();notice('已设为待重试，请返回工作台启动');}};
$('downloadReports').onclick=()=>{if(!p)return;download('reviewforge-reports-'+p.id+'.json',{project_id:p.id,title:p.title,generated_at:new Date().toISOString(),completed:percent(p)===100,gates:p.gates,usage:p.usage,reports:agents.map(a=>({agent_id:a.agent_id,name:a.name,responsibility:a.responsibility,...p.tasks[a.agent_id]})),events:p.events});};
const exportDraft=el('button','','导出综述草稿');$('downloadReports').parentElement.append(exportDraft);exportDraft.onclick=()=>{if(!p)return;const body=p.tasks.W06.output?.payload.edited_manuscript||p.tasks.W08.output?.payload.author_manuscript;if(!body){notice('主笔或全文编辑尚未交付综述文本');return;}const sections=['# '+p.title,'> 草稿导出。主笔状态：'+labels[p.tasks.W08.state]+'；全文编辑状态：'+labels[p.tasks.W06.state]+'。需结合严谨表达角色的修改意见与作者核查。',body];for(const [id,keys] of [['W07',['captions','references','ai_and_license_disclosures']],['W10',['sentence_level_edits','scope_and_causality_checks','preserved_uncertainties']]])for(const key of keys){const content=p.tasks[id].output?.payload[key];if(content)sections.push('## '+id+' / '+key,content);}download('reviewforge-draft-'+p.id+'.md',sections.join('\n\n'),'text/markdown');};
$('connect').onclick=async()=>{const config=settings();if(!config.key){notice('请输入 API key');return;}$('connect').disabled=true;connected=false;try{let usage;await completion(config,[{role:'user',content:'仅回复 OK，这是模型连接测试。'}],AbortSignal.timeout(90000),()=>{},u=>usage=u);connected=true;text('connection','已连接 · '+config.model);notice('连接成功。测试请求会产生少量模型 token 用量。');if(p){if(usage){p.usage.input+=usage.prompt_tokens||0;p.usage.output+=usage.completion_tokens||0;}else p.usage.unknown++;await save();render();}}catch(e){notice(e.message);text('connection','连接失败');}finally{$('connect').disabled=false;}};
for(const id of ['base','key','model'])$(id).oninput=()=>{connected=false;text('connection','配置变更 · 请测试连接');};
$('forget').onclick=()=>{$('key').value='';connected=false;text('connection','密钥已清除');};
window.addEventListener('beforeunload',e=>{if(running){e.preventDefault();e.returnValue='当前角色仍在执行';}});
try{agents=(await(await fetch('./agents.json',{cache:'no-cache'})).json()).agents;if(agents.length!==44)throw Error('44 角色合同载入失败');if(!navigator.locks)throw Error('请使用支持 Web Locks 的现代浏览器');const ownsSession=await new Promise(resolve=>{void navigator.locks.request('reviewforge-v1-session',{ifAvailable:true},lock=>{resolve(!!lock);return lock?new Promise(()=>{}):undefined;});});if(!ownsSession)throw Error('另一标签页已打开工作台，请关闭另一页后刷新；防止重复执行和覆盖本地项目');for(const a of agents)$('reportRole').append(new Option(a.agent_id+' · '+a.name,a.agent_id));await initDB();render();}catch(e){notice('初始化失败：'+e.message);document.querySelectorAll('button,input,textarea,select').forEach(n=>n.disabled=true);}
